{
  imports = [
    ./accounts-daemon.nix
    ./acipd.nix
    ./auditd.nix
    ./autovt.nix
    ./avahi.nix
    ./blocky.nix
    ./bluetooth.nix
    ./chrony.nix
    ./colord.nix
    ./cups.nix
    ./dbus-broker.nix
    ./dbus.nix
    ./display-manager.nix
    ./docker.nix
    ./geoclue2.nix
    ./modemmanager.nix
    ./nix-daemon.nix
    ./nscd.nix
    ./reload-systemd-vconsole-setup.nix
    ./rescue.nix
    ./rtkit.nix
    ./systemd-ask-password-console.nix
    ./systemd-ask-password-wall.nix
    ./systemd-emergency-mode.nix
    ./systemd-journald.nix
    ./systemd-machined.nix
    ./systemd-rfkill.nix
    ./systemd-udevd.nix
    ./tmp-tmpfs.nix
    ./udisks2.nix
    ./wpa_supplicant.nix
  ];
}
